// apps/vue-demos/src/views/list/index.vue
<template>
  <div class="bg-#fff min-h-[calc(100vh-48px)]">
    <h1 class="mt-0 text-center">List</h1>
    <van-list>
      <van-cell class="text-center" v-for="item in 10" :key="item" :title="`Item ${item}`" clickable to="detail" />
    </van-list>
  </div>
</template>

<script setup lang="ts"></script>

<style scoped></style>

// apps/react-demos/src/other-views/route-transition/List.tsx
import { List } from '@youknown/react-ui/src'
import { useNavigate } from 'react-router-dom'

export default function ListPage() {
  const navigate = useNavigate()
  const list = Array(10)
    .fill(null)
    .map((_, index) => index)
  return (
    <div className="bg-orange min-h-[calc(100vh-48px)] p-10px">
      <List>
        {list.map(item => (
          <List.Item
            key={item}
            clickable
            onClick={() => {
              navigate('/component/route_transition/detail')
            }}
          >
            Item {item}
          </List.Item>
        ))}
      </List>
    </div>
  )
}
